version: "3.5"

services:
  trust-anchor.org:
    image: ghcr.io/freddi301/federation-django:0.0.0
    ports:
      - "8000:8000"
    networks:
      - oidc-network
  relying-party.org:
    image: ghcr.io/freddi301/relying-party-express-react:0.0.0
    ports:
      - "3000:3000"
    networks:
      - oidc-network
      
networks:
  oidc-network:
